excluded:
  - Pods
  - .build
  - DerivedData

opt_in_rules:
  - attributes
  - closure_spacing
  - collection_alignment
  - explicit_init
  - explicit_self
  - first_where
  - force_unwrapping
  - operator_usage_whitespace
  - sorted_imports
  - vertical_whitespace_closing_braces

line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 80

force_cast: error
force_try: error
force_unwrapping: error

identifier_name:
  min_length: 
    warning: 3
  excluded:
    - id
    - URL
    - x
    - y
    - to

reporter: "xcode"
