disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - sorted_imports
  - vertical_whitespace_closing_braces

included:
  - Stockbar

excluded:
  - Pods
  - .build
  - DerivedData

line_length: 120
function_body_length: 60
type_body_length: 300
file_length: 500

identifier_name:
  min_length: 1
  max_length: 40

cyclomatic_complexity:
  warning: 10
  error: 20 