#!/bin/bash

# Stockbar Unit Test Setup & Execution Script
# This script helps set up and run the Phase 5 unit tests

echo "=========================================="
echo "Stockbar v2.3.0 - Unit Test Setup"
echo "=========================================="
echo ""

PROJECT_DIR="/Users/josh/Downloads/Stockbar Claude/Stockbar"
cd "$PROJECT_DIR"

echo "📋 Test files available:"
ls -1 StockbarTests/*Tests.swift 2>/dev/null | grep -E "RiskMetrics|TechnicalIndicator|MenuBar|PortfolioAnalytics" || echo "  (test files not found)"
echo ""

echo "=========================================="
echo "Setup Instructions"
echo "=========================================="
echo ""
echo "The test files have been created but need a test target in Xcode:"
echo ""
echo "1️⃣  Open Xcode:"
echo "   open \"$PROJECT_DIR/Stockbar.xcodeproj\""
echo ""
echo "2️⃣  Create Unit Test Target:"
echo "   • File → New → Target..."
echo "   • Select 'macOS' tab"
echo "   • Choose 'Unit Testing Bundle'"
echo "   • Click 'Next'"
echo "   • Product Name: 'StockbarTests'"
echo "   • Team: (your team or 'None')"
echo "   • Target to be Tested: 'Stockbar'"
echo "   • Click 'Finish'"
echo ""
echo "3️⃣  Add existing test files to target:"
echo "   • In Project Navigator, locate 'StockbarTests' folder"
echo "   • Select these 4 files (⌘-click to select multiple):"
echo "     - RiskMetricsServiceTests.swift"
echo "     - TechnicalIndicatorServiceTests.swift"
echo "     - MenuBarFormattingServiceTests.swift"
echo "     - PortfolioAnalyticsServicesTests.swift"
echo "   • Open File Inspector (⌥⌘1)"
echo "   • Under 'Target Membership', check 'StockbarTests'"
echo ""
echo "   Alternatively, you can:"
echo "   • Delete the auto-generated 'StockbarTests.swift' file"
echo "   • Right-click 'StockbarTests' group → Add Files to 'Stockbar'..."
echo "   • Navigate to StockbarTests folder"
echo "   • Select the 4 test files"
echo "   • Ensure 'StockbarTests' target is checked"
echo "   • Click 'Add'"
echo ""
echo "4️⃣  Run tests:"
echo "   • Press ⌘U (or Product → Test)"
echo "   • View results in Test Navigator (⌘6)"
echo ""
echo "=========================================="
echo "Quick Start"
echo "=========================================="
echo ""
echo "Run this command to open Xcode:"
echo ""
echo "  open \"$PROJECT_DIR/Stockbar.xcodeproj\""
echo ""
echo "Then follow steps 2-4 above."
echo ""
echo "=========================================="
echo "Test Coverage"
echo "=========================================="
echo ""
echo "✅ RiskMetricsServiceTests (17 tests)"
echo "   • VaR, Sharpe, Sortino, Beta, Max Drawdown"
echo ""
echo "✅ TechnicalIndicatorServiceTests (19 tests)"
echo "   • SMA, EMA, RSI, MACD, Bollinger Bands"
echo ""
echo "✅ MenuBarFormattingServiceTests (23 tests)"
echo "   • All display modes, templates, formatting"
echo ""
echo "✅ PortfolioAnalyticsServicesTests (21 tests)"
echo "   • Correlation matrix, sector analysis"
echo ""
echo "📊 Total: 80+ comprehensive unit tests"
echo ""
echo "=========================================="
echo "Troubleshooting"
echo "=========================================="
echo ""
echo "If tests don't appear after adding files:"
echo "  • Clean build folder: ⇧⌘K"
echo "  • Rebuild: ⌘B"
echo "  • Check Target Membership in File Inspector"
echo ""
echo "If you get 'No such module Stockbar' errors:"
echo "  • Ensure @testable import Stockbar is present"
echo "  • Verify 'Stockbar' target is set as dependency"
echo ""
echo "Expected Results:"
echo "  • Green checkmarks (✓) = Pass"
echo "  • Red X marks (✗) = Fail"
echo "  • Target: >80% pass rate"
echo ""
echo "Good luck! 🚀"
echo ""
